# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
ADMIN_EMAIL: joelbrewer01@gmail.com
ADMIN_PASSWORD: woohoohoo

  #stripe keys
STRIPE_API_KEY: sk_test_UtcewaeBlLgJTrSe7ceMhI43 
STRIPE_PUBLIC_KEY: pk_test_75iH1MZN5wkhCLBeX58XH83n

  #aws keys
AWS_ACCESS_KEY_ID: AKIAJCUBDXV4AJAGVA6A 
AWS_SECRET_ACCESS_KEY: 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
